### PR TITLE
Support for opening group tabs by middle click

### PR DESCRIPTION
**Pull request by DarkVen0m**
https://github.com/OlegWock/anori/issues/202

### CODE REVIEW

**Comment by OlegWock** [comment]
Hello @DarkVen0m, thanks for the PR. What is the reason to change element from `a` to `div`?

**Comment by DarkVen0m** [comment]
> Hello @DarkVen0m, thanks for the PR. What is the reason to change element from `a` to `div`?

Just makes more sense to me than having `a` tag without href attribute

**Comment by OlegWock** [comment]
Using div with onClick handler makes it inaccessible for screen readers (and considered bad practice in general). Could you revert it back to `<a>` or change it to be a `<button>`?

**Comment by DarkVen0m** [comment]
Good point. I'll change it.
But if you care about a11y here, you should also look into another navigation problem. WidgetCard has tabindex, which makes it a focusable element. Like here.
image
But actual `<a>` is nested deeper and is focusable as well.
image
This leads to at least two problems: you have to "double" tab to switch between two elements, and the actual action isn't visually highlighted. Button tag will lead to similar problem.
So in my opinion, either `<a>` or `<button>` tag should be on top, or it should be refactored some other way to call action on the upper-level element.

**Comment by DarkVen0m** [comment]
> Using div with onClick handler makes it inaccessible for screen readers (and considered bad practice in general). Could you revert it back to `<a>` or change it to be a `<button>`?

Changed to `<button>`

**Comment by OlegWock** [comment]
I lack required knowledge and free time to seriously work on a11y in Anori, I just try to not make it worse :D

Thanks for changes, I'm going to merge this

**Comment by DarkVen0m** [comment]
Yeah, I understand. Thanks for the great extension anyway!

**Pull request merged**
