### PR TITLE
Add support for custom search providers and disabling search providers

### PR DESCRIPTION
**Pull request by DarkEden-coding**
This pull request supports adding your own search provider, whatever you want! It also lets you disable the ones you never use *cough cough bing*.

### CODE REVIEW

**Comment by OlegWock** [comment]
Hello @DarkEden-coding. Thanks for the PR! I currently have a lot going on, so I won't be able to properly review and merge it this week, but I just wanted to let you know that I saw it and eventually will get to it.

**Comment by DarkEden-coding** [comment]
No problem! Thanks for the update!

**Comment by OlegWock** [comment]
Hello @DarkEden-coding. I started reviewing the PR but noticed that there are quite a few of issues and it will require not just a couple of comments/fixes from me, but reworking a significant part of this PR. Testing it locally, I noticed that your UI changes don't reflect Anori style (e.g. using native checkboxes instead of `<Checkbox />` component, absence of spacing between inputs) which makes me think you didn't check how similar UI is implemented in other parts of Anori.

Taking this into consideration, I won't be merging this PR. I appreciate the time you spent working on it, but as a maintainer of Anori I have to keep project's quality bar. Please note that even without merging this PR, you can compile your fork of Anori and use it in your browser instead of version of Anori from Chrome/Firefox store.

**Comment by DarkEden-coding** [comment]
Ah, sorry about that, I totally understand not being able to merge. It's my first time contributing and I apologize for any time waisted on your end. Thank you for making and maintaining this project!

**Pull request closed without merging**
