### PR TITLE
feat: Add open-in-new-window toggle switch to bookmark widget

### PR DESCRIPTION
**Pull request by bil0ak**
This pull request introduces a new feature to the bookmark widget, allowing users to choose whether the bookmark opens in a new window or not. The changes include:

Added a toggle switch to the widget configuration screen for the "Open in New Window" option
Updated the styling of the configuration screen to accommodate the new toggle switch
Modified the widget behavior to open the bookmark in a new window/tab based on the user's preference
With this update, users can now have better control over the behavior of their bookmarks. Please review the changes and let me know if you have any suggestions or concerns. Looking forward to getting this merged!

### CODE REVIEW

**Comment by OlegWock** [comment]
Hello @bil0ak. Thank you for contributing to the Anori!

I checked your PR, wouldn't this open bookmark in new tab (instead of new window)?

And I have couple of change requests, I'll comment on related code

**Comment by bil0ak** [comment]
> Hello @bil0ak. Thank you for contributing to the Anori!
> 
> ~I checked your PR, wouldn't this open bookmark in new tab (instead of new window)?~
> 
> Sorry, didn't noticed you mention this in your message.
> 
> And I have couple of change requests, I'll comment on related code

Oh sorry, I didn't even notice that i've been typing window instead of tap.

I also have been trying to create a "Custome Theme" but it might take a bit long, currently I'm busy with college.

Anyway, happy to help.

**Comment by OlegWock** [comment]
Yeah, custom theme might be quite hard to tackle. It involves a bit of UI challenge as well as working with file api

**Review by OlegWock — CHANGES_REQUESTED** [review]
Sorry for delay @bil0ak, I thought I posted comments already but it turns out I needed to press separate button to make them visible

**Comment by bil0ak** [comment]
Sorry for being late. I didn't see the notification until today.

This update should work now. Please tell me if you need any other changes.

**Comment by OlegWock** [comment]
Hello @bil0ak! Thanks again for your contribution. I'm planning to change license for this project from current MIT license to AGPL (full text can be found [here](https://choosealicense.com/licenses/agpl-3.0/)). Since project now has piece of code you wrote I need your consent for such change. Please reply to let me know if you agree with license switch

Essentially, nothing changes for you or extension user's, but I need your consent for legal reasons. AGPL is less permissive license and I'm making this switch to avoid (potential) situations when someone decides to profit from project and start selling Anori (or software based on Anori).

**Comment by OlegWock** [comment]
Hello @bil0ak! Sorry to ping you again, but I need your consent or I'll be forced to remove code contributed by you

**Comment by bil0ak** [comment]
@OlegWock Im sorry for replying late. im not getting any notifications for these pings.
I might be late but still.. yes you have my presmission to do as you please with my code. incliding changing the license.

**Comment by OlegWock** [comment]
Thanks, I'll re-include your contribution in next version of Anori

**Pull request merged**
