### PR TITLE
Complete zh-CN translations

### PR DESCRIPTION
**Pull request by TheSnowfield**

### CODE REVIEW

**Comment by OlegWock** [comment]
Looks great, thanks!

**Comment by OlegWock** [comment]
Hey @TheSnowfield, this is how translation currently looks in the extension in normal mode (font size 16px): 

CleanShot 2023-07-14 at 17 46 33

And in compact mode (font size 14px):

CleanShot 2023-07-14 at 17 51 33


I'm not sure about font size, is current font size is easily readable (especially in compact mode) or should I increase it? From what I read 16px  should be fine, but I'd like to hear from the native

**Comment by TheSnowfield** [comment]
LGTM. It's pretty nice!

**Comment by TheSnowfield** [comment]
I prefer 16px too

**Comment by OlegWock** [comment]
I just uploaded latest version (v1.9.1) to stores, it might take a few days for them to check submission and after that Chinese translation will be available for all users.

Thanks again @TheSnowfield !

**Comment by TheSnowfield** [comment]
> 

you're welcome. 😊
I will be continuing to translate follow versions.

**Pull request merged**
